# Generated by Django 5.0.6 on 2024-06-09 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PetStoreApp", "0002_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("totalamount", models.FloatField()),
                (
                    "cid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetStoreApp.customer",
                    ),
                ),
                (
                    "pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetStoreApp.pet",
                    ),
                ),
            ],
            options={
                "db_table": "Cart",
            },
        ),
    ]
