# Generated by Django 5.0.6 on 2024-06-19 06:19

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PetStoreApp", "0004_order"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="pet",
            managers=[
                ("cpetobj", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="pet",
            name="slug",
            field=models.SlugField(default=""),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paymentstatus", models.CharField(default="Pending", max_length=100)),
                ("transactionid", models.CharField(max_length=200)),
                ("paymentmode", models.CharField(default="PayPal", max_length=100)),
                (
                    "customerid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetStoreApp.customer",
                    ),
                ),
                (
                    "oid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetStoreApp.order",
                    ),
                ),
            ],
            options={
                "db_table": "Payment",
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordernumber", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("totalprice", models.IntegerField()),
                ("created_at", models.DateField(auto_now=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "customerid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetStoreApp.customer",
                    ),
                ),
                (
                    "productid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetStoreApp.pet",
                    ),
                ),
                (
                    "paymentid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetStoreApp.payment",
                    ),
                ),
            ],
            options={
                "db_table": "OrderDetail",
            },
        ),
    ]
