# Generated by Django 4.2.7 on 2024-06-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empid", models.IntegerField(max_length=30)),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("age", models.IntegerField(max_length=10)),
                ("address", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "Employee",
            },
        ),
    ]
