# Generated by Django 4.2.7 on 2024-06-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EmployeeSearchApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="employee",
            name="empid",
            field=models.IntegerField(),
        ),
    ]
